services:
  mariadb:
    build: ./srcs/requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    volumes: 
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
  wordpress:
    build: ./srcs/requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
  nginx:
    build: ./srcs/requirements/nginx
    container_name: nginx
    restart: unless-stopped
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

networks:
  inception:
    driver: bridge