services:
  mariadb:
    build: ./srcs/requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    secrets:
      - db_root_password.txt
      - db_password.txt
      - db_admin_password.txt
    env_file: .env
    volumes: 
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
  wordpress:
    build: ./srcs/requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    secrets:
      - wp_admin_password.txt
      - wp_user_password.txt
      - db_password.txt
    env_file: .env
    volumes: 
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
  nginx:
    build: ./srcs/requirements/nginx
    container_name: nginx
    restart: unless-stopped
    env_file: .env
    ports:
      - "443:443"
    volumes: 
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress

secrets:
  db_root_password.txt:
    file: ./secrets/db_root_password.txt
  db_password.txt:
    file: ./secrets/db_password.txt
  db_admin_password.txt:
    file: ./secrets/db_admin_password.txt
  wp_admin_password.txt:
    file: ./secrets/wp_admin_password.txt
  wp_user_password.txt:
    file: ./secrets/wp_user_password.txt

volumes:
  mariadb_data:
  wordpress_data:

networks:
  inception: