services:
  mariadb:
    build: ./srcs/requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    volumes: 
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
  wordpress:
    build: ./srcs/requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    volumes: 
      - wordpress_data:/var/www/wordpress
    networks:
      - inception

volumes:
  mariadb_data:
  wordpress_data:

networks:
  inception: